name: screenshots
description: Auto-generation of screenshots for Apple and Play Stores using emulators and simulators with support for locales. Compatible with fastlane for upload to both stores.
version: 0.1.5
homepage: https://github.com/mmcc007/screenshots
author: Maurice McCabe <mmcc007@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  args: ^1.5.1
  yaml: ^2.1.15
  resource: ^2.1.5
  path: ^1.6.2

dev_dependencies:
  test: ^1.5.1+1

executables:
  screenshots: main